### ISSUE TITLE
Failure with    error: Illegal package name: "..."

### ISSUE THREAD

**Issue by qzic** [talsma-ict/umldoclet#668]
## Expected Behavior
I expect to have javadoc site built. I'm attempting to generate the javadoc in a netbeans java project

## Actual Behavior

```
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:javadoc (default-cli) on project RPi_Drums: An error has occurred in Javadoc report generation: 
Exit code: 2 - error: Illegal package name: "..."
1 error

Command line was: "C:\Program Files\Java\zulu17.54.21-ca-jdk17.0.13-win_x64\zulu17.54.21-ca-jdk17.0.13-win_x64\bin\javadoc.exe" @options @packages

Refer to the generated Javadoc files in 'C:\Users\Quentin\Documents\NetBeansProjects\MAVEN\RPi_Drums\target\site\apidocs' dir.
```

## Steps to Reproduce the Problem
rt-click on project name and select generate javadoc

## Specifications

  - Version plugin 2.2.1:
  - Platform: win 10
  - Java version: 11

I suspect that the error is caused because I have a java file in the default package so it's in the folder of the groupId.
Maybe your plugin expects java files to always be in not default packages 

my target/site/packages file after the failure contains

ca.qzic
ca.qzic.drumpedals.commonBT
ca.qzic.drumpedals.DrumPedals
ca.qzic.drumpedals.GUI
ca.qzic.drumpedals.MidiUtil
ca.qzic.drumpedals.Networks
ca.qzic.drumpedals.Presets
ca.qzic.drumpedals.Util

so, i have a java file in .../ca/qzic folder

**Comment by qzic** [comment]
Hmmm? Well I have another project with the same structure, a java file in the default package and your plugin works beautifully  so that can't be the problem.

Any suggestions on how to debug or get you more useful info on this error?

**Comment by sjoerdtalsma** [comment]
You could try to manually run the javadoc command on the commandline with the generated @options and @packages files (which should normally remain in your build folder if the javadoc fails).

You can then also add debugging (see `javadoc --help`) for more info.

**Comment by sjoerdtalsma** [comment]
I would look at package names with strange characters in them (spaces, comma's, etc) in the packages generated by netbeans.

I don't have netbeans myself and normally use IntelliJ + maven to run my javadoc.

**Comment by qzic** [comment]
Well, java packages/classes can't have spaces (probably not commas either). I do use underscores but that is totally legal. I have two projects and one exhibits the problem (luckily a simple one) and another that does not. So I'm going to work on the offending project and determine what the problem is.

**I ran the plugin from command line and this error shows up in the middle of all the output:**

```
[INFO] Generating "Maven Coordinates" report --- maven-project-info-reports-plugin:3.9.0:dependency-info
[WARNING] An issue has occurred with maven-project-info-reports-plugin:3.9.0:dependency-info report, skipping LinkageError 'void org.apache.maven.doxia.sink.Sink.verbatim()', please report an issue to Maven dev team.
java.lang.NoSuchMethodError: 'void org.apache.maven.doxia.sink.Sink.verbatim()'
```
**followed by (at the end):**

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project Rpi_Util: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 2 - error: Illegal package name: "..."
[ERROR] 1 error
[ERROR]
[ERROR] Command line was: "C:\Program Files\Java\jdk-21\bin\javadoc.exe" @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'C:\Users\Quentin\Documents\NetBeansProjects\MAVEN\Rpi_Util\target\apidocs' dir.
[ERROR]
```
**under target/reports/apidocs I see javadoc.bat, options and packages files.
In options I see where the problem is. Note the 2nd line after -sourcepath is ... ** 
The options file is removed in the case of the successful project run so I can't compare. Under ...main/java I have package ca/qzic/rpi_util and a bunch of class files in the folder. Note that ca.qzic is my groupId. The should the source path be  .../main/java/rpi_util or maybe the ... should be rpi_util **

```
-classpath
'C:/Users/Quentin/.m2/repository/org/jfree/jfreechart/1.5.3/jfreechart-1.5.3.jar'
-doclet
'nl.talsmasoftware.umldoclet.UMLDoclet'
-docletpath
'C:/Users/Quentin/.m2/repository/nl/talsmasoftware/umldoclet/2.2.1/umldoclet-2.2.1.jar'
-encoding
'UTF-8'
-protected
--release
17
-sourcepath
'C:/Users/Quentin/Documents/NetBeansProjects/MAVEN/Rpi_Util/src/main/java'
...
-author
-bottom
'Copyright &#169; 2025. All rights reserved.'
-charset
'UTF-8'
-d
'C:/Users/Quentin/Documents/NetBeansProjects/MAVEN/Rpi_Util/target/reports/apidocs'
-docencoding
'UTF-8'
-doctitle
'Rpi_Util 1.0 API'
-use
-version
-windowtitle
'Rpi_Util 1.0 API'
```

**Comment by qzic** [comment]
Here is my pom.xml from the problem project:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>ca.qzic</groupId>
    <artifactId>Rpi_Util</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
    <dependencies>
        <!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-project-info-reports-plugin -->
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-project-info-reports-plugin</artifactId>
            <version>3.9.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.jfree/jfreechart -->
        <dependency>
            <groupId>org.jfree</groupId>
            <artifactId>jfreechart</artifactId>
            <version>1.5.3</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.11.2</version>
                <executions>
                    <execution>
                        <phase>site</phase>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <doclet>nl.talsmasoftware.umldoclet.UMLDoclet</doclet>
                    <docletArtifact>
                        <groupId>nl.talsmasoftware</groupId>
                        <artifactId>umldoclet</artifactId>
                        <version>2.2.1</version>
                    </docletArtifact>
                    <additionalOptions>
                        <additionalOption>...</additionalOption>
                    </additionalOptions>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>${maven.compiler.source}</release>
                    <target>${maven.compiler.target}</target>
                    <showDeprecation>true</showDeprecation>
                    <showWarnings>true</showWarnings>
                    <verbose>false</verbose>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by qzic** [comment]
**SOLVED**

I had uncommented a line in the plugin
                    <additionalOptions>
                        
                    </additionalOptions>
so I had 
                    <additionalOptions>
                        <additionalOption>...</additionalOption>
                    </additionalOptions>

**This is what caused the failure!**

Just for fun I tried with 
                    <additionalOptions>
                        <additionalOption></additionalOption>
                    </additionalOptions>

That failed too so best to keep that line commented.

**Comment by qzic** [comment]
I've ben thinking that while this 
```
                    <additionalOptions>
                        <additionalOption>...</additionalOption>
                    </additionalOptions>
```
should result in an error. It would be nice if it pointed you back to look at the plugin.

However, I think the plugin should handle the following without error.
```
                    <additionalOptions>
                        <additionalOption></additionalOption>
                    </additionalOptions>
```
at most a warning that an additionOption is emply

**Comment by sjoerdtalsma** [comment]
Glad to see the issue was resolved!

The error processing of the additional options is delegated to Javadoc's Standard doclet implementation.
Upfront validation should be done in the javadoc maven plugin, if anywhere.
I don't think the UMLDoclet plays a part in this problem. Feel free to open a new issue if it does.

Thank you anyway for reporting this and for using the doclet.
